name: PageSpeed Insights Audit Weekly
on:
  schedule:
    - cron: "0 0 * * 1" # 매주 월요일 00:00에 실행
  workflow_dispatch: # 수동 실행 버튼 활성화

jobs:
  performance-audit:
    name: PSI Audit
    runs-on: ubuntu-latest
    strategy:
      matrix:
        url_path: ["", "39", "38"]
    steps:
      - name: PageSpeed Insights
        uses: jakepartusch/psi-action@v1.3
        with:
          url: https://${{ vars.BLOG_DOMAIN }}/${{ matrix.url_path }}
          key: ${{ secrets.PSI_API_KEY }}
          # threshold: 90 # 원하는 경우 최소 점수 기준 설정 가능
